### ISSUE TITLE
add userController routes

### ISSUE THREAD

**Issue by anjaliroland** [bear-muna/bite-buddies#24]
## User Story
AS A user of this application
I WANT to be able to login and out
SO THAT I can protect my tracked applications

## Acceptance Criteria
- [ ] POST ‘/’ route to create req.body
- [ ] POST ‘/login’ route
- [ ] POST ‘/logout’ route

**Comment by muttaqin1** [comment]
Hey @anjaliroland ! 
I am interested to contribute on this issue.can you please assign me?
